apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: oyaraouf
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 1
      timeoutSeconds: 15
      containers:
      - image: europe-west1-docker.pkg.dev/oyaraouf/oyaraouf/oyaraouf:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
  traffic:
  - percent: 100
    latestRevision: true
